spring:
  application:
    name: ProjectPractic
  jpa:
    hibernate:
      ddl-auto: update
    datasource:
      username: postgres
      password: postgres
      url: jdbc:postgresql://localhost:5432/database

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 3000