package ru.projectpractic.utils;

public enum ExceptionType {
    USER_NOT_FOUND,
    USERNAME_ALREADY_IN_USE,
    ENTITY_NOT_FOUND,
    ENTITY_ALREADY_EXISTS,
    ANY_EXCEPTION,


    //validation
    EMPTY_USERNAME,
    TOO_LONG_USERNAME,
    TOO_SHORT_USERNAME,
    EMPTY_PASSWORD,
    TOO_LONG_PASSWORD,
    TOO_SHORT_PASSWORD,
    PASSWORD_PATTERN_ERROR,
    COURSE_OF_STUDY_EMPTY_ERROR,
    COURSE_OF_STUDY_VALUE_ERROR,
    EMPTY_FACULTY,
    TOO_LONG_FACULTY,
    TOO_SHORT_FACULTY,
    EMPTY_RESUME,
    TOO_LONG_RESUME,
    TOO_SHORT_RESUME,
    EMPTY_DESCRIPTION,
    TOO_LONG_DESCRIPTION,
    TOO_SHORT_DESCRIPTION,
    EMPTY_TITLE,
    TOO_LONG_TITLE,
    TOO_SHORT_TITLE,
    EMPTY_DEPARTMENT,
    TOO_LONG_DEPARTMENT,
    TOO_SHORT_DEPARTMENT,
    EMPTY_ORGANIZATION,
    TOO_LONG_ORGANIZATION,
    TOO_SHORT_ORGANIZATION,
    TOO_LONG_COVER_LETTER
}
